@startuml
!include .\\.\Program.puml
!include .\\Controllers\CampaignController.puml
!include .\\Controllers\EmailController.puml
!include .\\Controllers\EmailTemplateController.puml
!include .\\Controllers\PhishingController.puml
!include .\\Controllers\ReportingController.puml
!include .\\Controllers\UsersController.puml
!include .\\Data\WeatherForecast.puml
!include .\\Data\WeatherForecastService.puml
!include .\\Models\Campaign.puml
!include .\\Models\DailyEmailStats.puml
!include .\\Models\EmailDTO.puml
!include .\\Models\EmailResult.puml
!include .\\Models\EmailTemplate.puml
!include .\\Models\ExcelReportGenerator.puml
!include .\\Models\PdfReportGenerator.puml
!include .\\Models\PhishingReport.puml
!include .\\Models\PhishingTest.puml
!include .\\Models\Recipient.puml
!include .\\Models\SuspiciusWords.puml
!include .\\Models\User.puml
!include .\\Pages\Error.cshtml.puml
!include .\\Services\CampaignService.puml
!include .\\Services\EmailService.puml
!include .\\Services\EmailTemplateService.puml
!include .\\Services\ICampaignInterface.puml
!include .\\Services\IEmailInterface.puml
!include .\\Services\IPhishingInterface.puml
!include .\\Services\IUserService.puml
!include .\\Services\PhishingService.puml
!include .\\Services\ReportingService.puml
!include .\\Services\UserService.puml
!include .\\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0\BlazorSimuladorJGF.AssemblyInfo.puml
!include .\\obj\Debug\net8.0\BlazorSimuladorJGF.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0\BlazorSimuladorJGF.RazorAssemblyInfo.puml
@enduml
